// <auto-generated />
namespace EntityFrameWork_CrudDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Book_Cat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Book_Cat));
        
        string IMigrationMetadata.Id
        {
            get { return "202210051816448_Book_Cat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
